### ISSUE TITLE
wrong interpretation of primaryKey forces unnecessary uniqueness constraints

### ISSUE THREAD

**Issue by akariv** [frictionlessdata/tableschema-py#194]
```
$ python
Python 3.6.1 (default, Mar 27 2017, 00:25:54)
>>> import tableschema
>>> open("bla.csv", "w").write("""id1,id2,value
... a,a,1
... a,b,2
... b,a,3
... b,b,4
... """)
38
>>> t=tableschema.Table("bla.csv", schema={
... "fields":[{"name":"id1", "type":"string"}, {"name":"id2", "type":"string"}, {"name":"value","type":"integer"}], "primaryKey": ["id1", "id2"]})
<tableschema.table.Table object at 0x10ddfc898>
>>> it=t.iter()
>>> list(it)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/adam/.pyenv/versions/3.6.1/lib/python3.6/site-packages/tableschema/table.py", line 102, in iter
    raise exceptions.CastError(message)
tableschema.exceptions.CastError: Field "id1" duplicates in row "3"
```

Since `id1` and `id2` are the primary key _together_, the uniqueness constraint should not be imposed on each one of these columns.

**Comment by roll** [comment]
Related https://github.com/frictionlessdata/goodtables-py/issues/215
