### ISSUE TITLE
Error when retrieving schema descriptor from string

### ISSUE THREAD

**Issue by pajachiet** [frictionlessdata/tableschema-py#239]
`Schema` can't load stream, because it first try to parse it as an URL.

Place of the error in the code
https://github.com/frictionlessdata/tableschema-py/blob/master/tableschema/helpers.py#L30

Code to reproduce the error
```python
from tableschema import Schema

schema = Schema({"fields": [{"name": "city", }]})
schema.save('tmp.json')

with open('tmp.json', 'w') as f:
    Schema(f)
```

Error message
```python
Traceback (most recent call last):
  File "/xxx/venv/lib/python3.7/site-packages/tableschema/helpers.py", line 30, in retrieve_descriptor
    if six.moves.urllib.parse.urlparse(source).scheme in config.REMOTE_SCHEMES:
…
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/parse.py", line 107, in <genexpr>
    return tuple(x.decode(encoding, errors) if x else '' for x in args)
AttributeError: '_io.TextIOWrapper' object has no attribute 'decode'
…

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/xxx/venv/lib/python3.7/site-packages/tableschema/schema.py", line 30, in __init__
    descriptor = helpers.retrieve_descriptor(descriptor)
  File "/xxx/venv/lib/python3.7/site-packages/tableschema/helpers.py", line 43, in retrieve_descriptor
    raise exceptions.LoadError('Can\'t load descriptor')
tableschema.exceptions.LoadError: Can't load descriptor
```

**Comment by roll** [comment]
CLOSED in #240
