### ISSUE TITLE
Python library issue

### ISSUE THREAD

**Issue by helenabarb** [frictionlessdata/tableschema-py#271]
# Overview
I tried to install this library so I could use the CKAN libraries. I get the following errors when I try to install. I am using Python 3.8.1 32 bit. please help.

Building wheel for cchardet (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\hgross\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\hgross\\AppData\\Local\\Temp\\pip-install-u1bjjel0\\cchardet\\setup.py'"'"'; __file__='"'"'C:\\Users\\hgross\\AppData\\Local\\Temp\\pip-install-u1bjjel0\\cchardet\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\hgross\AppData\Local\Temp\pip-wheel-xmp77uf8'
       cwd: C:\Users\hgross\AppData\Local\Temp\pip-install-u1bjjel0\cchardet\
  Complete output (56 lines):
  cythonize: ['src/cchardet\\_cchardet.pyx']
  c:\users\hgross\appdata\local\programs\python\python38-32\lib\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Users\hgross\AppData\Local\Temp\pip-install-u1bjjel0\cchardet\src\cchardet\_cchardet.pyx
    tree = Parsing.p_module(s, pxd, full_module_name)
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win32-3.8
  creating build\lib.win32-3.8\cchardet
  copying src\cchardet\version.py -> build\lib.win32-3.8\cchardet
  copying src\cchardet\__init__.py -> build\lib.win32-3.8\cchardet
  running build_ext
  building 'cchardet._cchardet' extension
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\hgross\AppData\Local\Temp\pip-install-u1bjjel0\cchardet\setup.py", line 115, in <module>
      setup(
    File "c:\users\hgross\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\__init__.py", line 144, in setup
      return distutils.core.setup(**attrs)
    File "c:\users\hgross\appdata\local\programs\python\python38-32\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "c:\users\hgross\appdata\local\programs\python\python38-32\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "c:\users\hgross\appdata\local\programs\python\python38-32\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "c:\users\hgross\appdata\local\programs\python\python38-32\lib\site-packages\wheel\bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "c:\users\hgross\appdata\local\programs\python\python38-32\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\hgross\appdata\local\programs\python\python38-32\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "c:\users\hgross\appdata\local\programs\python\python38-32\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "c:\users\hgross\appdata\local\programs\python\python38-32\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\hgross\appdata\local\programs\python\python38-32\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "c:\users\hgross\appdata\local\programs\python\python38-32\lib\distutils\command\build_ext.py", line 340, in run
      self.build_extensions()
    File "c:\users\hgross\appdata\local\programs\python\python38-32\lib\distutils\command\build_ext.py", line 449, in build_extensions
      self._build_extensions_serial()
    File "c:\users\hgross\appdata\local\programs\python\python38-32\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
      self.build_extension(ext)
    File "c:\users\hgross\appdata\local\programs\python\python38-32\lib\distutils\command\build_ext.py", line 528, in build_extension
      objects = self.compiler.compile(sources,
    File "c:\users\hgross\appdata\local\programs\python\python38-32\lib\distutils\_msvccompiler.py", line 360, in compile
      self.initialize()
    File "c:\users\hgross\appdata\local\programs\python\python38-32\lib\distutils\_msvccompiler.py", line 253, in initialize
      vc_env = _get_vc_env(plat_spec)
    File "c:\users\hgross\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\msvc.py", line 171, in msvc14_get_vc_env
      return EnvironmentInfo(plat_spec, vc_min_ver=14.0).return_env()
    File "c:\users\hgross\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\msvc.py", line 1623, in return_env
      if self.vs_ver >= 14 and isfile(self.VCRuntimeRedist):
    File "c:\users\hgross\appdata\local\programs\python\python38-32\lib\genericpath.py", line 30, in isfile
      st = os.stat(path)
  TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
  ----------------------------------------
  ERROR: Failed building wheel for cchardet
  Running setup.py clean for cchardet
Failed to build cchardet
Installing collected packages: cchardet, tabulator, tableschema
    Running setup.py install for cchardet ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\hgross\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\hgross\\AppData\\Local\\Temp\\pip-install-u1bjjel0\\cchardet\\setup.py'"'"'; __file__='"'"'C:\\Users\\hgross\\AppData\\Local\\Temp\\pip-install-u1bjjel0\\cchardet\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\hgross\AppData\Local\Temp\pip-record-rw75exk5\install-record.txt'
--single-version-externally-managed --compile --install-headers 'c:\users\hgross\appdata\local\programs\python\python38-32\Include\cchardet'
         cwd: C:\Users\hgross\AppData\Local\Temp\pip-install-u1bjjel0\cchardet\
    Complete output (58 lines):
    cythonize: ['src/cchardet\\_cchardet.pyx']
    c:\users\hgross\appdata\local\programs\python\python38-32\lib\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Users\hgross\AppData\Local\Temp\pip-install-u1bjjel0\cchardet\src\cchardet\_cchardet.pyx
      tree = Parsing.p_module(s, pxd, full_module_name)
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.8
    creating build\lib.win32-3.8\cchardet
    copying src\cchardet\version.py -> build\lib.win32-3.8\cchardet
    copying src\cchardet\__init__.py -> build\lib.win32-3.8\cchardet
    running build_ext
    building 'cchardet._cchardet' extension
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\hgross\AppData\Local\Temp\pip-install-u1bjjel0\cchardet\setup.py", line 115, in <module>
        setup(
      File "c:\users\hgross\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\hgross\appdata\local\programs\python\python38-32\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\hgross\appdata\local\programs\python\python38-32\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\users\hgross\appdata\local\programs\python\python38-32\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\hgross\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\users\hgross\appdata\local\programs\python\python38-32\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\users\hgross\appdata\local\programs\python\python38-32\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\hgross\appdata\local\programs\python\python38-32\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\hgross\appdata\local\programs\python\python38-32\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "c:\users\hgross\appdata\local\programs\python\python38-32\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\hgross\appdata\local\programs\python\python38-32\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\hgross\appdata\local\programs\python\python38-32\lib\distutils\command\build_ext.py", line 340, in run
        self.build_extensions()
      File "c:\users\hgross\appdata\local\programs\python\python38-32\lib\distutils\command\build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "c:\users\hgross\appdata\local\programs\python\python38-32\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "c:\users\hgross\appdata\local\programs\python\python38-32\lib\distutils\command\build_ext.py", line 528, in build_extension
        objects = self.compiler.compile(sources,
      File "c:\users\hgross\appdata\local\programs\python\python38-32\lib\distutils\_msvccompiler.py", line 360, in compile
        self.initialize()
      File "c:\users\hgross\appdata\local\programs\python\python38-32\lib\distutils\_msvccompiler.py", line 253, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "c:\users\hgross\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\msvc.py", line 171, in msvc14_get_vc_env
        return EnvironmentInfo(plat_spec, vc_min_ver=14.0).return_env()
      File "c:\users\hgross\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\msvc.py", line 1623, in return_env
        if self.vs_ver >= 14 and isfile(self.VCRuntimeRedist):
      File "c:\users\hgross\appdata\local\programs\python\python38-32\lib\genericpath.py", line 30, in isfile
        st = os.stat(path)
    TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\hgross\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\hgross\\AppData\\Local\\Temp\\pip-install-u1bjjel0\\cchardet\\setup.py'"'"'; __file__='"'"'C:\\Users\\hgross\\AppData\\Local\\Temp\\pip-install-u1bjjel0\\cchardet\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\hgross\AppData\Local\Temp\pip-record-rw75exk5\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\hgross\appdata\local\programs\python\python38-32\Include\cchardet' Check the logs for full command output.
PS C:\Use

**Comment by roll** [comment]
Hi, could you please try to install from a scratch?

It should be fixed by https://github.com/frictionlessdata/tabulator-py#v138
